### ISSUE TITLE
Cannot use helm chart with CLI parameters

### ISSUE THREAD

**Issue by przemolb** [deliveryhero/helm-charts#121]
I am trying to test various values from CLI using the following command:
```
helm install overprovisioner deliveryhero/cluster-overprovisioner --set deployments[0].resources.requests.cpu="2000m"
```
and I am getting the following error:
```
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: [unknown object type "nil" in Deployment.metadata.labels.app.cluster-overprovisioner/deployment, unknown object type "nil" in Deployment.spec.selector.matchLabels.app.cluster-overprovisioner/deployment, unknown object type "nil" in Deployment.spec.template.metadata.labels.app.cluster-overprovisioner/deployment]
```

A command without any parameters work well:
```
helm install overprovisioner deliveryhero/cluster-overprovisioner
```
Any hint what is wrong ?

**Comment by max-rocket-internet** [comment]
Hi @przemolb 
The problem is that when you supply part of an item in a list, in your example `deployments[0]`, all the [other parts of that item](https://github.com/deliveryhero/helm-charts/blob/master/stable/cluster-overprovisioner/values.yaml#L46-L71) from the default values file are not used. The reason is that lists are not merged across values or values files. In this case `name` is required so you can do this:

```
helm install overprovisioner deliveryhero/cluster-overprovisioner --set deployments[0].resources.requests.cpu="2000m" --set deployments[0].name=default
```

Make sense?

**Comment by przemolb** [comment]
@max-rocket-internet  thanks - that works.
